### ISSUE TITLE
Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred.

### ISSUE THREAD

**Issue by mostafa88** [aria2/aria2#1112]
I am using arai2.exe version 1.33.1 on windows 7sp1 to download a file from https link. But the following error occurred.

> Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause: No connection could be made because the target machine actively refused it. 

I can download the same file on other operating systems 7, 8, 8.1 and 10. I also turn off the system firewall and the error still exist.

would you please help me.

[screenshot](https://pasteboard.co/H3jUCwb.jpg)

**Comment by mostafa88** [comment]
This issue occured becase of a proxy was already set on the system and in the time of starting download, the porxy not running and aria2 cannot download the file.
So the issue should be closed.

**Comment by magicuniverse-azeem** [comment]
I'm getting the same exact error with aria2c 1.33.0, 1.33.1 and 1.34.0. How were you able to fix this?

**Comment by TrainerRoshi** [comment]
Same error.
`Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

**Comment by dedo1911** [comment]
I just came across the same issue and this fixed my problem: https://github.com/aria2/aria2/issues/1440
I've added `--disable-ipv6`

**Comment by FuccDucc** [comment]
I just want to leave this in case it saves someone else's day: in my case it happened due to a Windows hosts file entry

in C:\Windows\System32\drivers\etc > "hosts", there was lines that blocked the destination from which i was trying to fetch files. In my case, i was using aria2 /aria2c in the context of uupdump Windows ISO downloading, so the culprit entries were:

0.0.0.0 tlu.dl.delivery.mp.microsoft.com
0.0.0.0 dl.delivery.mp.microsoft.com

(in my case also, these lines were in the hosts file as a result of running Windows debloaters & anti telemetry function in it)

This proves it's not limited to ipv6 stuff, also that switch didn't help in my case. It can also happen because for any PC or OS-related reason, you can't reach the destination host properly (as in: traffic gets blocked or filtered), Check the destinations in any such blocklist, hosts file included

**Comment by Git-Maniac** [comment]
> I just came across the same issue and this fixed my problem: #1440 I've added `--disable-ipv6`

Where do I have to add _--disable-ipv6_ ?

Because in Automatic1111 _webui-user.bat_ is _COMMANDLINE_ARGS=--disable-ipv6_ not recognized.

Thanks.

**Comment by Doublefire-Chen** [comment]
> I just came across the same issue and this fixed my problem: [#1440](https://github.com/aria2/aria2/issues/1440) I've added `--disable-ipv6`

Thank you, it works for me.

**Comment by Doublefire-Chen** [comment]
> > I just came across the same issue and this fixed my problem: [#1440](https://github.com/aria2/aria2/issues/1440) I've added `--disable-ipv6`
> 
> Where do I have to add _--disable-ipv6_ ?
> 
> Because in Automatic1111 _webui-user.bat_ is _COMMANDLINE_ARGS=--disable-ipv6_ not recognized.
> 
> Thanks.

I think you make a mistake, Automatic1111 _webui-user.bat_ is stable diffusion web UI instead of aria2.
