### ISSUE TITLE
Increment number of max-connection-per-server

### ISSUE THREAD

**Issue by lardissone** [aria2/aria2#126]
Is there a way to increment this max to something higher than 16?

Why is this limitation?

**Comment by Saren-Arterius** [comment]
> 16 is plenty. Too easy to do DOS.
> If you want more, change the source code as you like.

1. Aria2 is not a great tool for DoS.
2. If Aria2 is will be used for a tool for DoS, the attacker could change to a higher value and re-compile it. So why bother limit it in source code?
3. Server host could easily block the offending connections.
4. If we need it, we know what we are doing.

Therefore, the 16 limit is not necessary. Please re-consider.

**Comment by recolic** [comment]
Azure official tool `azcopy` creates 128 connections by default, and has 1300Mbps download speed in MSFT intranet.
But aria2c has only 70 Mbps download speed. TCP window size limit in a high latency connection restricts bandwidth of single connection. 

aria2c is "the ultra fast download utility", but it's not.

**Comment by expecttheunusual** [comment]
Besides, hackers could provide a malicious version of aria2c which has no 16-limit. Sure, you are protecting the servers, but doing so will indirectly put your clients at risk because you don't actually give the users what they want. It's like getting a porsche with an engine of a fucking tractor. It's usable for normal users but for those that want more out of it it get pretty annoying.

**Comment by 3052** [comment]
> Azure official tool `azcopy` creates 128 connections by default, and has 1300Mbps download speed in MSFT intranet. But aria2c has only 70 Mbps download speed. TCP window size limit in a high latency connection restricts bandwidth of single connection.

@recolic this is stupid because `azcopy` only works with Azure not as a general downloader

**Comment by recolic** [comment]
This is just a valid example showing why supporting more conns is useful.
I didn't mean u should download everything with my example....

Feb 17, 2025 16:32:08 3052 ***@***.***>:

**Comment by 3052** [comment]
its a terrible example because you cant download anything with AzCopy, only private Azure files, so its a dumb comparison

**Comment by recolic** [comment]
> its a terrible example because you cant download anything with AzCopy, only private Azure files, so its a dumb comparison

There's some misunderstanding.

I was **not** to compare two different softwares, azcopy vs aria2;
I was **not** to say, azcopy is better than aria2;
I was **not** to say, aria2 should copy exactly the same behavior; 
I was **not** to say, azcopy is superior to other software.

What I **am** trying to explain is: 
1. Such a scenario exists, that we reasonably need 128 or more parallel http conns while downloading from some http server in some network condition.
2. Azure is a reasonably common hosting provider. It's not some rare corner case. 
3. So, It's a lie that such scale of conn is always for attack or abuse.
4. Since a reasonable scenario exists, the restriction is unnecessary and obsolete. I believe it should be removed if you still agree with open source software common philosophy.
5. Always read all texts before reply.
