### ISSUE TITLE
Metadata and potential password leaks via --log=

### ISSUE THREAD

**Issue by RootUp** [aria2/aria2#1329]
Hi Team,

I am using aria2 version 1.33.1 on 4.15.0-43-generic 46-Ubuntu.

1. It was observed that URL's which gets downloaded via `--log=` attribute stored sensitive information. 
2. In combination with HTTP authentication a username and password can be part of the URL.
`aria2c --log=file  https://user:passwd@example.com/`
- In such case the log file contains password as well, sometimes URL's may contain secret tokens, e.g. private file shares on a file hosting service.
- In general storing metadata at unexpected places should be avoided.
3. However, if the above steps are repeated using the below URL the log file does not contains password.
`aria2c --log=file https://t.me/socks?server=inputzero.io&port=22&user=dhiraj&pass=MystrongPassw0rd`

Request team to have a look and validate.

**Comment by abergmann** [comment]
[CVE-2019-3500](https://nvd.nist.gov/vuln/detail/CVE-2019-3500) was assigned to this issue.

**Comment by tatsuhiro-t** [comment]
aria2 only masks credentials which follows "Authorization: Basic ".  No masking is made for userinfo subcomponent in URI.

I will change the code so that all authorization and cookie header fields are masked.
I have no plan masking userinfo in URL because it has been deprecated and considered insecure.

**Comment by tatsuhiro-t** [comment]
Fix committed via 37368130ca7de5491a75fd18a20c5c5cc641824a
