### ISSUE TITLE
Watch video while downloading

### ISSUE THREAD

**Issue by amilino** [aria2/aria2#1519]
Is it possible to download video over torrent and watch at the same time? Tried stream-piece-selector=inorder but it deosn't work?

**Comment by VaslD** [comment]
`stream-piece-selector` only applies to HTTP/FTP (i.e., "browser compatible") downloads. BitTorrent uses a different option called `bt-prioritize-piece` where you can prioritize the first few chunks (and the last few chunks) of each file.

But it really depends on the container (i.e., "filename"). Probably the most widely-used video container *Matroska* (*.mkv) specifies no particular order of its the contents, according to [this page](https://matroska.org/technical/diagram/index.html). Meaning unless you have the entire file available (or you have really fast network tranfer that works like the entire file is available on your computer, which is rarely the case with BT), it is almost impossible to play it properly. The only way to stream such file as if you're watching YouTube is either (1) having the website/uploader optimize their videos for streaming, which fixes the order of contents per a set standard; or (2) dynamically prioritize pieces according to what you already have and what they point to next. Not sure if Aria 2 supports this, even if it does you'll need to do some programming on your own to make it happen. Aria 2 is just a download manager after all, it knows nothing about videos.

You should just find another solution. I have come across two approaches in my past research but I don't guarantee they still exist or work:

- There are software that does No. (2) above automatically. They likely don't use Aria 2, but they take care of selecting which pieces to download, and all you need to do is feed them a magnet link and wait, preferably with patience.
- There are also services that download and convert video in BT to a streamable format for you, all done on their server. You give them a magnet link and they give you an address that you can open in your browser, then you can watch the video you requested like watching YouTube. This one usually requires much less wait time and much less bandwidth on your end compared to the other option, because the heavylifting is done on "other people's computer", but costs more.

**Comment by amilino** [comment]
Thank you for a detailed explanation.

**Comment by NextDev56** [comment]
"Transcoding begins with determining the duration of the content. Based on this duration a full HLS-playlist is generated with records of still non-existent 10 second fragments. When any of these fragments is accessed the new FFmpeg process is launched to convert the necessary fragment (in this case, only the necessary part of the torrent is downloaded). As soon as the fragmnet is converted, it is sent to the user. If the user suddenly rewound to another section, then the current FFmpeg process “falls asleep”, and somewhere already starts a new one. If the user came back, then the old process located nearby “wakes up” and continues its work. In the end, you get a whole seamless video. And yes, each conversion also runs in a separate container."

[webtor.io](url) seems to do the job quite well
