### ISSUE TITLE
Can not download from wupfile.com,  SSL/TLS handshake failure (80092013)

### ISSUE THREAD

**Issue by jc3213** [aria2/aria2#1704]
Download link: https://fs255.wupfile.com/d/ib3cowax3cidhs7qmeoalrerrid7thvbp6bfyojj53xtlbaidrt2sfg5skje4bqavluvmmte/Slow_Life_ga_Shitai_Daikensha_01s.rar
Reference link: https://wupfile.com/6zye4mjs52g3
It works yesterday though, but can't work today, here's the error log.

EDIT: I can download it with Chrome browser, but can't with Aria2

```
11/15 15:24:28 [ERROR] CUID#10 - Download aborted. URI=https://fs255.wupfile.com/d/ib3cowax3cidhs7qmeoalrerrid7thvbp6bfyojj53xtlbaidrt2sfg5skje4bqavluvmmte/Slow_Life_ga_Shitai_Daikensha_01s.rar 
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://fs255.wupfile.com/d/ib3cowax3cidhs7qmeoalrerrid7thvbp6bfyojj53xtlbaidrt2sfg5skje4bqavluvmmte/Slow_Life_ga_Shitai_Daikensha_01s.rar
-> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Error: The revocation function was unable to check revocation because the revocation server was offline. (80092013)
```

**Comment by agowa338** [comment]
In your case the server to check the validity of the TLS certificate against was offline/unreachable.
Either something in your network is blocking the connection, or that server simply is in an error state...

The only thing you could do is to manually validate the TLS certificate instead of having aria2 doing it for you.

**Comment by jc3213** [comment]
> In your case the server to check the validity of the TLS certificate against was offline/unreachable.
> Either something in your network is blocking the connection, or that server simply is in an error state...
I've been downloading files from `wupfile.com` using aria2 and chrome extension for months, and then aria2 suddenly can't download the uris. I've tried also to use proxy on the downloads, but they just don't work. I can download using chrome browser but can not download using aria2.

> The only thing you could do is to manually validate the TLS certificate instead of having aria2 doing it for you.
How to do this? Any manual or something?

**Comment by agowa338** [comment]
> I've been downloading files from `wupfile.com` using aria2 and chrome extension for months, and then aria2 suddenly can't download the uris. I've tried also to use proxy on the downloads, but they just don't work. I can download using chrome browser but can not download using aria2.

Google Chrome has a different logic to validate the validity of the certificate. For me the error aria2c throws is also different. It only complains about "not signed by known authorities or invalid". The certificate chain is therefore incomplete. I've checked using ssllabs.com for fs255.wupfile.com. The intermediate ca certificate is missing. Apparently google chrome does ship this certificate. cacertificates (what I suspect aria2 is using) however doesn't.
![image](https://user-images.githubusercontent.com/2544867/100048617-82e26c80-2e15-11eb-847c-eedb89e0cdce.png)

Therefore `--ca-certificate=/path/to/ca-certificates.crt` should do the trick, where the ca-certificates.crt file is the intermediate certificate from the above screenshot.

Because you now said you're using WinTLS I suspect you're using Windows? It's a bit different there. Windows should already include this certificate, otherwise import it into the windows intermediate ca certificates store.

> > The only thing you could do is to manually validate the TLS certificate instead of having aria2 doing it for you.
> 
> How to do this? Any manual or something? I've tried `--without-wintls` on aria2 document but it corrupt the program, and aria2 rpc won't be started

This cannot work, you basically disabled TLS on your client. It therefore is incapable of accessing any https sites...

**Comment by jc3213** [comment]
> The certificate chain is therefore incomplete. I've checked using ssllabs.com for fs255.wupfile.com. The intermediate ca certificate is missing. Apparently google chrome does ship this certificate. cacertificates (what I suspect aria2 is using) however doesn't.
 > Because you now said you're using WinTLS I suspect you're using Windows? It's a bit different there. Windows should already include this certificate, otherwise import it into the windows intermediate ca certificates store.

Chrome on Windows uses Windows' CA management, but Mozilla Firefox uses built-in CA management (as your pic). That's why this is weird because Chromium can download, but aria2 can't....  The aria2 has once worked until I come here and filed this issue. 

I'm wondering which CA cert is required for `wupfile.com`? How to get it... I've tried ssllabs.com that you provided, but it says `Certificate not available any longer`
