### ISSUE TITLE
JSON-RPC batch and system.multicall

### ISSUE THREAD

**Issue by sonnyp** [aria2/aria2#625]
I want to add a batch/multicall helper to aria2.js https://github.com/sonnyp/aria2.js/issues/10 and I have a few questions

1) By reading aria2 code/documentation it's unclear to me if there are conceptual/functional differences between the two or if system.multicall is simply batch for XML-RPC.

2) In the case there is no differences, should I prefer JSON-RPC batch over multicall?

> The secret token validation in aria2 is designed to take at least a certain amount of time to mitigate brute-force/dictionary attacks against the RPC interface. Therefore it is recommended to prefer Batch or system.multicall requests when appropriate. 

3) I don't follow the conclusion of the first sentence? Does it mean using batch/multicall is a way to reduce 'flooding' so that the brute-force/dictionary attack protection doesn't kick off for a large number of requests? What is the rate limit?

4) Does it mean batch/multicall should always be preferred over multiple requests? Even for WebSocket transport?

I'll be happy to send a documentation PR and see if I can clarify those points with your help.

**Comment by tatsuhiro-t** [comment]
The difference between these two is that batch call is only available to JSON-RPC, and it has slightly different request/response format.  Basically, they perform in the same way.  Personally, if JSON-RPC is used, I prefer batch method since it looks more like a JSON.

The documentation seems out of date now.  We penalize the failed authorization, but there is no penalty in successful one.

Using batch/multicall is potentially more efficient since the all requests in batch call can be sent in fewer packets, which could reduce latency.  This still holds true for WebSocket.  If you know the set of requests to send in advance, using batch/multicall is a good choice.   In general, batching multiple requests is good thing in RPC call because networking is considered as high cost operation.

**Comment by sonnyp** [comment]
Thanks

> Using batch/multicall is potentially more efficient since the all requests in batch call can be sent in fewer packets, which could reduce latency.

In theory yes (specially in the case of HTTP where the overhead is significant) but if one of the request of the batch takes 100ms more than any other within the same batch, you'll get a 100ms latency increase compared to individual request (because you'll have to wait for that longer operation to finish to receive the responses for shorter operations).

I don't understand the case for batching requests/responses over a low latency transport. Except if it provides support for atomic operations. Sending individual requests at once provides better latency than batching.

The only case where batching might be useful would be on mobile, by receiving all responses at once; the connection can idle sooner and increase battery life.

I'm thinking making the batch/multicall helper use JSON-RPC batching when used over HTTP and individual requests/responses when used over WebSocket. 

Please let me know if I get it wrong.

**Comment by tatsuhiro-t** [comment]
aria2 RPC response is supposed to be non-blocking, and it means it should be done 'quickly'. If you really need super fast response for a single request, regular non-batch RPC may be faster.  But unless you pack hundreds of RPC requests in a single batch, the difference may not be noticeable.

With low latency, yes, there may be no difference at all.  But in these days, everyone uses mobile, right?  Probably it is not the use case of your js lib, though.

**Comment by sonnyp** [comment]
Right, in any case it won't make a big difference but I find the topic interesting.

I'll simply make the multicall/batch helper always use JSON-RPC batch and let the users decide.
