### ISSUE TITLE
Why do you use autotools

### ISSUE THREAD

**Issue by andrew-aladev** [aria2/aria2#7]
There are many usefull modern build systems such as cmake. it have ctest that will work perfectly with your cppunit tests. cpack can provide convenient deb and rpm packages for current user platform. of course you can make cmake-tollchain and create build for any platform you want: i586, amd64, arm or for some shit platforms like win32, win64 and mac os

**Comment by navidR** [comment]
I think this has got to be reopened. With the recent push from Google (NDK compilation with CMake Toolchain file they provide with NDK is easy as using your default toolchain, their integration of CMake to gradle, etc), Microsoft (Integrating CMake to VS, providing [CMake based ](https://github.com/Microsoft/vcpkg)package management solution for C++) and other big companies to CMake. CMake has become de facto build system for most projects and companies. Despite its bad syntax, CMake gets the job done. The fact QtCreator, VisualStudio, Clion (and none of them do support Autotools at all) are trying to become better CMake based library shows how much attention it got in recent year.

I am not going to talk about hardness of Autotool usage, because there is no point. We all know how tedious it is to use autotools, specially for newcomers.

Waether we like it our not, Autotools is going to die. And I am happy about it. It was very useful and advanced tool for its time. But now CMake is the build system which industry settles in.

**Comment by YenForYang** [comment]
Agree 100% with @navidR. 

It is time.

**Comment by inCHOK-broken-earphone** [comment]
I'm working on the cross compiling of aria2, and I'd like to say that using autotools with android ndk is just like a shit, hoping move to cmake as quick as possible.

**Comment by xpol** [comment]
Agree
And I'm managed to build with cmake on macOS. But other system are not tested.
I will test on Windows later. if it works, I'll try to make a PR.

If any interested please see: https://github.com/xpol/aria2/tree/cmake .

**Comment by Cardinalinux** [comment]
> Agree
> And I'm managed to build with cmake on macOS. But other system are not tested.
> I will test on Windows later. if it works, I'll try to make a PR.
> 
> If any interested please see: https://github.com/xpol/aria2/tree/cmake .

Your cmake solution is awsome, it works well on macOS, thanks.

**Comment by KOLANICH** [comment]
@tatsuhiro-t
