### ISSUE TITLE
Option to download .torrent without downloading the files in the torrent

### ISSUE THREAD

**Issue by simonzack** [aria2/aria2#87]
There doesn't seem to be an option to download the .torrent file without downloading the files in the torrent. The only option I could find is in a build configuration.
I don't use aria2 as a torrent client, but I need to download the raw .torrent files so I could process them, or send them to other torrent clients, so this option would be very convenient.

**Comment by getmeacuboftea** [comment]
The correct answer is:
bt-metadata-only=true
bt-save-metadata=true
Since he want to get the "raw torrent file", so what he had should be a magnet link. follow-torrent shouldn't have any effect.
I know this is a very late reply, but I know someone else might stumble upon this issue. follow-torrent isn't the right answer.
