### ISSUE TITLE
Mac dmg file for version 1.31.0

### ISSUE THREAD

**Issue by alireza-amirsamimi** [aria2/aria2#894]
Hello
Please add Mac dmg file for [Aria2 Version 1.31.0](https://github.com/aria2/aria2/releases/tag/release-1.31.0) ,if it's available :)
We use your release files (for Windows and mac) in [Persepolis Download Manager](https://github.com/persepolisdm/persepolis) project. Aria2 is work like a charm in Gnu/Linux and Mac and Windows and BSD :)
Thank you 🙏

**Comment by devildant** [comment]
+1

**Comment by devildant** [comment]
hello, i see that inside the read me : 
`We use 3 numbers for aria2 version: MAJOR.MINOR.PATCH. We will ship MINOR update on 15th of every month. We may skip a release if we have no changes since the last release. `
he mac version can not be impacted by the changes of the 1.31,
maybe or maybe not :)

**Comment by tatsuhiro-t** [comment]
I think it is possible to build aria2 mac binary using https://github.com/aria2/aria2/blob/master/makerelease-osx.mk

**Comment by nmaier** [comment]
https://github.com/aria2/aria2/issues/936#issuecomment-308696829
